version: "3.8"

services:
  database:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:7.2.3"
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build: .
    depends_on:
      - database
      - redis
    environment: &common_app_env
      DEBUG: false
      SECRET_KEY: "${SECRET_KEY}"
      POSTGRES_HOST: "database"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      OTEL_PYTHON_DJANGO_INSTRUMENT: "${OTEL_PYTHON_DJANGO_INSTRUMENT}"
    ports: 
      - "8080:8000"

volumes:
    db-data: {}
    app_dev: {}
    prometheus: {}