version: "3.8"


services:
  database:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:7.2.3"
    ports:
      - "${REDIS_PORT}:6379"


  # Uses production docker images and configuration
  app_production:
    build: .
    depends_on:
      - database
      - redis
    environment: &common_app_env
      DEBUG: false
      SECRET_KEY: "${SECRET_KEY}"
      POSTGRES_HOST: "database"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
    ports: 
      - "${APP_PROD_PORT}:8000"

  # Uses local files on a volume for development convenience
  app_dev:
    image: python:3.10
    depends_on:
      - database
      - redis
    ports:
     - "${APP_DEV_PORT}:8000"
    working_dir: /app
    volumes:
     - type: bind
       source: ./
       target: /app 
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      <<: *common_app_env
      DEBUG: true
    entrypoint: "/app/start_dev.sh"

      

volumes:
    db-data: {}
    app_dev: {}